/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OAuth2Application struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	ClientId string `json:"client_id,omitempty"`
	// Used for more stringent verification of access to an application when creating a token.
	ClientSecret string `json:"client_secret,omitempty"`
	// Set to Public or Confidential depending on how secure the client device is.
	ClientType string `json:"client_type"`
	// Allowed URIs list, space separated
	RedirectUris string `json:"redirect_uris,omitempty"`
	// The Grant type the user must use for acquire tokens for this application.
	AuthorizationGrantType string `json:"authorization_grant_type"`
	// Set True to skip authorization step for completely trusted applications.
	SkipAuthorization bool `json:"skip_authorization,omitempty"`
	// Organization containing this application.
	Organization int32 `json:"organization"`
}
