/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Schedule struct {
	// A value representing the schedules iCal recurrence rule.
	Rrule string `json:"rrule"`
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	ExtraData *interface{} `json:"extra_data,omitempty"`
	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int32 `json:"inventory,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	JobType string `json:"job_type,omitempty"`
	JobTags string `json:"job_tags,omitempty"`
	SkipTags string `json:"skip_tags,omitempty"`
	Limit string `json:"limit,omitempty"`
	DiffMode bool `json:"diff_mode,omitempty"`
	Verbosity string `json:"verbosity,omitempty"`
	UnifiedJobTemplate int32 `json:"unified_job_template"`
	// Enables processing of this schedule.
	Enabled bool `json:"enabled,omitempty"`
	// The first occurrence of the schedule occurs on or after this time.
	Dtstart time.Time `json:"dtstart,omitempty"`
	// The last occurrence of the schedule occurs before this time, aftewards the schedule expires.
	Dtend time.Time `json:"dtend,omitempty"`
	// The next time that the scheduled action will run.
	NextRun time.Time `json:"next_run,omitempty"`
	Timezone string `json:"timezone,omitempty"`
	Until string `json:"until,omitempty"`
}
