/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JobHostSummary struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Job string `json:"job,omitempty"`
	Host int32 `json:"host,omitempty"`
	HostName string `json:"host_name,omitempty"`
	Changed int32 `json:"changed,omitempty"`
	Dark int32 `json:"dark,omitempty"`
	Failures int32 `json:"failures,omitempty"`
	Ok int32 `json:"ok,omitempty"`
	Processed int32 `json:"processed,omitempty"`
	Skipped int32 `json:"skipped,omitempty"`
	Failed bool `json:"failed,omitempty"`
	Ignored int32 `json:"ignored,omitempty"`
	Rescued int32 `json:"rescued,omitempty"`
}
