/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkflowJobNodeDetail struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	ExtraData *interface{} `json:"extra_data,omitempty"`
	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int32 `json:"inventory,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	JobType string `json:"job_type,omitempty"`
	JobTags string `json:"job_tags,omitempty"`
	SkipTags string `json:"skip_tags,omitempty"`
	Limit string `json:"limit,omitempty"`
	DiffMode bool `json:"diff_mode,omitempty"`
	Verbosity string `json:"verbosity,omitempty"`
	Job int32 `json:"job,omitempty"`
	WorkflowJob string `json:"workflow_job,omitempty"`
	UnifiedJobTemplate int32 `json:"unified_job_template,omitempty"`
	SuccessNodes []int32 `json:"success_nodes,omitempty"`
	FailureNodes []int32 `json:"failure_nodes,omitempty"`
	AlwaysNodes []int32 `json:"always_nodes,omitempty"`
	// If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node
	AllParentsMustConverge bool `json:"all_parents_must_converge,omitempty"`
	// Indicates that a job will not be created when True. Workflow runtime semantics will mark this True if the node is in a path that will decidedly not be ran. A value of False means the node may not run.
	DoNotRun bool `json:"do_not_run,omitempty"`
	// An identifier coresponding to the workflow job template node that this node was created from.
	Identifier string `json:"identifier,omitempty"`
}
