/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JobLaunch struct {
	CanStartWithoutUserInput bool `json:"can_start_without_user_input,omitempty"`
	PasswordsNeededToStart string `json:"passwords_needed_to_start,omitempty"`
	ExtraVars *interface{} `json:"extra_vars,omitempty"`
	Inventory int32 `json:"inventory,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	Limit string `json:"limit,omitempty"`
	JobTags string `json:"job_tags,omitempty"`
	SkipTags string `json:"skip_tags,omitempty"`
	JobType string `json:"job_type,omitempty"`
	Verbosity int32 `json:"verbosity,omitempty"`
	DiffMode bool `json:"diff_mode,omitempty"`
	Credentials []int32 `json:"credentials,omitempty"`
	CredentialPasswords string `json:"credential_passwords,omitempty"`
	AskScmBranchOnLaunch bool `json:"ask_scm_branch_on_launch,omitempty"`
	AskVariablesOnLaunch bool `json:"ask_variables_on_launch,omitempty"`
	AskTagsOnLaunch bool `json:"ask_tags_on_launch,omitempty"`
	AskDiffModeOnLaunch bool `json:"ask_diff_mode_on_launch,omitempty"`
	AskSkipTagsOnLaunch bool `json:"ask_skip_tags_on_launch,omitempty"`
	AskJobTypeOnLaunch bool `json:"ask_job_type_on_launch,omitempty"`
	AskLimitOnLaunch bool `json:"ask_limit_on_launch,omitempty"`
	AskVerbosityOnLaunch bool `json:"ask_verbosity_on_launch,omitempty"`
	AskInventoryOnLaunch bool `json:"ask_inventory_on_launch,omitempty"`
	AskCredentialOnLaunch bool `json:"ask_credential_on_launch,omitempty"`
	SurveyEnabled string `json:"survey_enabled,omitempty"`
	VariablesNeededToStart string `json:"variables_needed_to_start,omitempty"`
	CredentialNeededToStart string `json:"credential_needed_to_start,omitempty"`
	InventoryNeededToStart string `json:"inventory_needed_to_start,omitempty"`
	JobTemplateData string `json:"job_template_data,omitempty"`
	Defaults string `json:"defaults,omitempty"`
}
