/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Inventory struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	// Organization containing this inventory.
	Organization int32 `json:"organization"`
	// Kind of inventory being represented.
	Kind string `json:"kind,omitempty"`
	// Filter that will be applied to the hosts of this inventory.
	HostFilter string `json:"host_filter,omitempty"`
	// Inventory variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
	// This field is deprecated and will be removed in a future release. Flag indicating whether any hosts in this inventory have failed.
	HasActiveFailures bool `json:"has_active_failures,omitempty"`
	// This field is deprecated and will be removed in a future release. Total number of hosts in this inventory.
	TotalHosts int32 `json:"total_hosts,omitempty"`
	// This field is deprecated and will be removed in a future release. Number of hosts in this inventory with active failures.
	HostsWithActiveFailures int32 `json:"hosts_with_active_failures,omitempty"`
	// This field is deprecated and will be removed in a future release. Total number of groups in this inventory.
	TotalGroups int32 `json:"total_groups,omitempty"`
	// This field is deprecated and will be removed in a future release. Flag indicating whether this inventory has any external inventory sources.
	HasInventorySources bool `json:"has_inventory_sources,omitempty"`
	// Total number of external inventory sources configured within this inventory.
	TotalInventorySources int32 `json:"total_inventory_sources,omitempty"`
	// Number of external inventory sources in this inventory with failures.
	InventorySourcesWithFailures int32 `json:"inventory_sources_with_failures,omitempty"`
	// Flag indicating the inventory is being deleted.
	PendingDeletion bool `json:"pending_deletion,omitempty"`
}
