/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CredentialType struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Kind string `json:"kind"`
	Namespace string `json:"namespace,omitempty"`
	Managed string `json:"managed,omitempty"`
	// Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax.
	Inputs *interface{} `json:"inputs,omitempty"`
	// Enter injectors using either JSON or YAML syntax. Refer to the documentation for example syntax.
	Injectors *interface{} `json:"injectors,omitempty"`
}
