/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkflowJobLaunch struct {
	AskInventoryOnLaunch bool `json:"ask_inventory_on_launch,omitempty"`
	AskLimitOnLaunch bool `json:"ask_limit_on_launch,omitempty"`
	AskScmBranchOnLaunch bool `json:"ask_scm_branch_on_launch,omitempty"`
	CanStartWithoutUserInput bool `json:"can_start_without_user_input,omitempty"`
	Defaults string `json:"defaults,omitempty"`
	ExtraVars string `json:"extra_vars,omitempty"`
	Inventory int32 `json:"inventory,omitempty"`
	Limit string `json:"limit,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	SurveyEnabled string `json:"survey_enabled,omitempty"`
	VariablesNeededToStart string `json:"variables_needed_to_start,omitempty"`
	NodeTemplatesMissing string `json:"node_templates_missing,omitempty"`
	NodePromptsRejected string `json:"node_prompts_rejected,omitempty"`
	WorkflowJobTemplateData string `json:"workflow_job_template_data,omitempty"`
	AskVariablesOnLaunch bool `json:"ask_variables_on_launch,omitempty"`
}
