/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InventoryVariableData struct {
	// Inventory variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
}
