/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CredentialInputSource struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Description string `json:"description,omitempty"`
	InputFieldName string `json:"input_field_name"`
	Metadata *interface{} `json:"metadata,omitempty"`
	TargetCredential int32 `json:"target_credential"`
	SourceCredential int32 `json:"source_credential"`
}
