/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type WorkflowJobTemplate struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	LastJobRun time.Time `json:"last_job_run,omitempty"`
	LastJobFailed bool `json:"last_job_failed,omitempty"`
	NextJobRun time.Time `json:"next_job_run,omitempty"`
	Status string `json:"status,omitempty"`
	ExtraVars string `json:"extra_vars,omitempty"`
	// The organization used to determine access to this template.
	Organization int32 `json:"organization,omitempty"`
	SurveyEnabled bool `json:"survey_enabled,omitempty"`
	AllowSimultaneous bool `json:"allow_simultaneous,omitempty"`
	AskVariablesOnLaunch bool `json:"ask_variables_on_launch,omitempty"`
	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int32 `json:"inventory,omitempty"`
	Limit string `json:"limit,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	AskInventoryOnLaunch bool `json:"ask_inventory_on_launch,omitempty"`
	AskScmBranchOnLaunch bool `json:"ask_scm_branch_on_launch,omitempty"`
	AskLimitOnLaunch bool `json:"ask_limit_on_launch,omitempty"`
	// Service that webhook requests will be accepted from
	WebhookService string `json:"webhook_service,omitempty"`
	// Personal Access Token for posting back the status to the service API
	WebhookCredential int32 `json:"webhook_credential,omitempty"`
}
