/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Host struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Inventory int32 `json:"inventory"`
	// Is this host online and available for running jobs?
	Enabled bool `json:"enabled,omitempty"`
	// The value used by the remote inventory source to uniquely identify the host
	InstanceId string `json:"instance_id,omitempty"`
	// Host variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
	HasActiveFailures string `json:"has_active_failures,omitempty"`
	HasInventorySources string `json:"has_inventory_sources,omitempty"`
	LastJob string `json:"last_job,omitempty"`
	LastJobHostSummary int32 `json:"last_job_host_summary,omitempty"`
	// The date and time ansible_facts was last modified.
	AnsibleFactsModified time.Time `json:"ansible_facts_modified,omitempty"`
}
