/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SchedulePreview struct {
	// A value representing the schedules iCal recurrence rule.
	Rrule string `json:"rrule"`
}
