/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ActivityStream struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	// The action taken with respect to the given object(s).
	Operation string `json:"operation"`
	// A summary of the new and changed values when an object is created, updated, or deleted
	Changes string `json:"changes,omitempty"`
	// For create, update, and delete events this is the object type that was affected. For associate and disassociate events this is the object type associated or disassociated with object2.
	Object1 string `json:"object1"`
	// Unpopulated for create, update, and delete events. For associate and disassociate events this is the object type that object1 is being associated with.
	Object2 string `json:"object2"`
	// When present, shows the field name of the role or relationship that changed.
	ObjectAssociation string `json:"object_association,omitempty"`
	// The cluster node the activity took place on.
	ActionNode string `json:"action_node,omitempty"`
	// When present, shows the model on which the role or relationship was defined.
	ObjectType string `json:"object_type,omitempty"`
}
