/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExecutionEnvironment struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	// The organization used to determine access to this execution environment.
	Organization int32 `json:"organization,omitempty"`
	// The full image location, including the container registry, image name, and version tag.
	Image string `json:"image"`
	Managed string `json:"managed,omitempty"`
	Credential int32 `json:"credential,omitempty"`
	// Pull image before running?
	Pull string `json:"pull,omitempty"`
}
