/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkflowJobTemplateNodeCreateApproval struct {
	// The amount of time (in seconds) before the approval node expires and fails.
	Timeout int32 `json:"timeout,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
}
