/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkflowJobTemplateNodeDetail struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	ExtraData *interface{} `json:"extra_data,omitempty"`
	// Inventory applied as a prompt, assuming job template prompts for inventory
	Inventory int32 `json:"inventory,omitempty"`
	ScmBranch string `json:"scm_branch,omitempty"`
	JobType string `json:"job_type,omitempty"`
	JobTags string `json:"job_tags,omitempty"`
	SkipTags string `json:"skip_tags,omitempty"`
	Limit string `json:"limit,omitempty"`
	DiffMode bool `json:"diff_mode,omitempty"`
	Verbosity string `json:"verbosity,omitempty"`
	WorkflowJobTemplate string `json:"workflow_job_template"`
	UnifiedJobTemplate int32 `json:"unified_job_template,omitempty"`
	SuccessNodes []int32 `json:"success_nodes,omitempty"`
	FailureNodes []int32 `json:"failure_nodes,omitempty"`
	AlwaysNodes []int32 `json:"always_nodes,omitempty"`
	// If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node
	AllParentsMustConverge bool `json:"all_parents_must_converge,omitempty"`
	// An identifier for this node that is unique within its workflow. It is copied to workflow job nodes corresponding to this node.
	Identifier string `json:"identifier,omitempty"`
}
