/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Project struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	// Local path (relative to PROJECTS_ROOT) containing playbooks and related files for this project.
	LocalPath string `json:"local_path,omitempty"`
	// Specifies the source control system used to store the project.
	ScmType string `json:"scm_type,omitempty"`
	// The location where the project is stored.
	ScmUrl string `json:"scm_url,omitempty"`
	// Specific branch, tag or commit to checkout.
	ScmBranch string `json:"scm_branch,omitempty"`
	// For git projects, an additional refspec to fetch.
	ScmRefspec string `json:"scm_refspec,omitempty"`
	// Discard any local changes before syncing the project.
	ScmClean bool `json:"scm_clean,omitempty"`
	// Track submodules latest commits on defined branch.
	ScmTrackSubmodules bool `json:"scm_track_submodules,omitempty"`
	// Delete the project before syncing.
	ScmDeleteOnUpdate bool `json:"scm_delete_on_update,omitempty"`
	Credential int32 `json:"credential,omitempty"`
	// The amount of time (in seconds) to run before the task is canceled.
	Timeout int32 `json:"timeout,omitempty"`
	// The last revision fetched by a project update
	ScmRevision string `json:"scm_revision,omitempty"`
	LastJobRun time.Time `json:"last_job_run,omitempty"`
	LastJobFailed bool `json:"last_job_failed,omitempty"`
	NextJobRun time.Time `json:"next_job_run,omitempty"`
	Status string `json:"status,omitempty"`
	// The organization used to determine access to this template.
	Organization int32 `json:"organization,omitempty"`
	// Update the project when a job is launched that uses the project.
	ScmUpdateOnLaunch bool `json:"scm_update_on_launch,omitempty"`
	// The number of seconds after the last project update ran that a new project update will be launched as a job dependency.
	ScmUpdateCacheTimeout int32 `json:"scm_update_cache_timeout,omitempty"`
	// Allow changing the SCM branch or revision in a job template that uses this project.
	AllowOverride bool `json:"allow_override,omitempty"`
	// Local absolute file path containing a custom Python virtualenv to use
	CustomVirtualenv string `json:"custom_virtualenv,omitempty"`
	// The default execution environment for jobs run using this project.
	DefaultEnvironment int32 `json:"default_environment,omitempty"`
	LastUpdateFailed bool `json:"last_update_failed,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
