/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProjectPlaybooks struct {
	// Array of playbooks available within this project.
	Playbooks string `json:"playbooks,omitempty"`
}
