/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Notification struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	NotificationTemplate int32 `json:"notification_template,omitempty"`
	Error_ string `json:"error,omitempty"`
	Status string `json:"status,omitempty"`
	NotificationsSent int32 `json:"notifications_sent,omitempty"`
	NotificationType string `json:"notification_type"`
	Recipients string `json:"recipients,omitempty"`
	Subject string `json:"subject,omitempty"`
	// Notification body
	Body string `json:"body,omitempty"`
}
