/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProjectInventories struct {
	// Array of inventory files and directories available within this project, not comprehensive.
	InventoryFiles string `json:"inventory_files,omitempty"`
}
