/*
 * Snippets API
 *
 * Test description
 *
 * API version: v1
 * Contact: contact@snippets.local
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserCredentialSerializerCreate struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Related *interface{} `json:"related,omitempty"`
	SummaryFields *interface{} `json:"summary_fields,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	// Specify the type of credential you want to create. Refer to the documentation for details on each type.
	CredentialType int32 `json:"credential_type"`
	Managed string `json:"managed,omitempty"`
	// Enter inputs using either JSON or YAML syntax. Refer to the documentation for example syntax.
	Inputs *interface{} `json:"inputs,omitempty"`
	Kind string `json:"kind,omitempty"`
	Cloud string `json:"cloud,omitempty"`
	Kubernetes string `json:"kubernetes,omitempty"`
	// Write-only field used to add user to owner role. If provided, do not give either team or organization. Only valid for creation.
	User int32 `json:"user,omitempty"`
}
